openapi: 3.0.3
info:
  title: LabWork Collection API
  description: API для управления коллекцией объектов класса LabWork и дополнительными операциями
  version: 1.0.0
servers:
  - url: https://localhost:8080
components:
  schemas:
    LabWork:
      type: object
      allOf:
        - type: object
          properties:
            id:
              type: integer
              format: int32
              minimum: 1
              example: 1
            creationDate:
              type: string
              format: date-time
              nullable: false
              example: 2024-09-12T10:00:00Z
        - $ref: '#/components/schemas/LabWorkDetails'
    LabWorkDetails:
      type: object
      properties:
        name:
          type: string
          nullable: false
          minLength: 1
          example: Лабораторная работа 1
        coordinates:
          $ref: '#/components/schemas/Coordinates'
        minimalPoint:
          type: number
          format: float
          minimum: 0
          exclusiveMinimum: true
          example: 10.5
        difficulty:
          $ref: '#/components/schemas/Difficulty'
        author:
          $ref: '#/components/schemas/Person'
    Coordinates:
      type: object
      properties:
        x:
          type: integer
          format: int32
          maximum: 592
          example: 100
        y:
          type: number
          format: float
          maximum: 892
          nullable: false
          example: 100.5
    Person:
      type: object
      properties:
        name:
          type: string
          nullable: false
          minLength: 1
          example: Иван Иванов
        birthday:
          type: string
          format: date-time
          nullable: false
          example: 2024-09-12T00:00:00Z
        weight:
          type: integer
          format: int32
          nullable: false
          minimum: 1
          example: 10
        location:
          $ref: '#/components/schemas/Location'
    Location:
      type: object
      properties:
        x:
          type: integer
          format: int32
          example: 50
        y:
          type: integer
          format: int64
          example: 1000
        name:
          type: string
          maxLength: 783
          nullable: true
          example: Где-то
    Difficulty:
      type: string
      enum:
        - VERY_EASY
        - EASY
        - NORMAL
        - IMPOSSIBLE
        - INSANE
      example: NORMAL
      nullable: true
paths:
  /labworks:
    get:
      summary: Получить массив лабораторных работ
      parameters:
        - name: sort
          in: query
          description: Поля для сортировки с указанием порядка, например 'desc(creationDate),asc(name)' или '-creationDate,+name'
          required: false
          schema:
            type: string
        - name: filter
          in: query
          description: Фильтрация по полям, например 'minimalPoint=gte:10&minimalPoint=lt:100'
          required: false
          schema:
            type: string
        - name: pageNumber
          in: query
          description: Номер страницы
          required: false
          schema:
            type: integer
            minimum: 0
        - name: pageSize
          in: query
          description: Размер страницы
          required: false
          schema:
            type: integer
            minimum: 1
            default: 10
      responses:
        '200':
          description: Успешный ответ с массивом лабораторных работ
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LabWork'
        '400':
          description: Некорректные параметры запроса
        '404':
          description: Лабораторные работы не найдены
    post:
      summary: Добавить новую лабораторную работу
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LabWorkDetails'
        required: true
      responses:
        '200':
          description: Лабораторная работа успешно добавлена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LabWorkDetails'          
        '400':
          description: Некорректные данные для добавления лабораторной работы
  /labworks/{labwork-id}:
    get:
      summary: Получить лабораторную работу по ID
      parameters:
        - name: labwork-id
          in: path
          required: true
          schema:
            type: integer
            format: int32
            nullable: false
            minimum: 1
            example: 10
      responses:
        '200':
          description: Успешный ответ с лабораторной работой
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LabWork'      
        '400':
          description: Некорректный ID лабораторной работы
        '404':
          description: Лабораторная работа не найдена
    put:
      summary: Обновить лабораторную работу
      parameters:
        - name: labwork-id
          in: path
          required: true
          schema:
            type: integer
            format: int32
            nullable: false
            minimum: 1
            example: 10
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LabWorkDetails'
      responses:
        '200':
          description: Лабораторная работа успешно обновлена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LabWork' 
        '400':
          description: Некорректные данные для обновления лабораторной работы
        '404':
          description: Лабораторная работа не найдена
    delete:
      summary: Удалить лабораторную работу
      parameters:
        - name: labwork-id
          in: path
          required: true
          schema:
            type: integer
            format: int32
            nullable: false
            minimum: 1
            example: 10
      responses:
        '204':
          description: Лабораторная работа успешно удалена
        '404':
          description: Лабораторная работа не найдена
  /labworks/minimalPoint/sum:
    get:
      summary: Рассчитать сумму значений поля minimalPoint для всех объектов
      responses:
        '200':
          description: Сумма значений поля minimalPoint
          content:
            application/json:
              schema:
                type: number
                format: float
        '404':
          description: Лабораторные работы не найдены
  /labworks/difficulty/min:
    get:
      summary: Вернуть один объект с минимальным значением поля difficulty
      responses:
        '200':
          description: Успешный ответ с объектом, значение поля difficulty которого минимально
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LabWork'
        '404':
          description: Лабораторные работы не найдены
  /labworks/author/count:
    get:
      summary: Вернуть количество объектов, значение поля author которых равно заданному
      parameters:
        - name: value
          in: query
          required: true
          description: Значение для фильтрации по полю author
          schema:
            type: string
      responses:
        '200':
          description: Количество лабораторных работ, заданного автора
          content:
            application/json:
              schema:
                type: integer
        '404':
          description: Лабораторные работы не найдены
        